language: python
python:
  - "2.7"
sudo: false
cache:
  pip: true
  directories:
    - "~/.platformio"
env:
  - PLATFORMIO_CI_SRC=src
  - PLATFORMIO_BUILD_FLAGS="-O3 -Wall -flto=3"
install:
  - pip install -U setuptools pip
  - pip install -U platformio
script:
  - platformio ci $PLATFORMIO_BUILD_FLAGS --board=leonardo --board=uno --lib="lib/Average" --lib="lib/Button" --lib="lib/Fsm" --lib="lib/LEDFader" --lib="lib/MIDI" --lib="lib/StackArray" --lib="lib/Streaming" --lib="lib/digitalWriteFast"
