language: python
python:
  - "2.7"
sudo: false
cache:
  directories:
    - "~/.platformio"
env:
  - PLATFORMIO_CI_SRC=src
install:
#   - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
  - pip install -U platformio
script:
  - platformio ci --board=teensy31 --lib="lib/Average" --lib="lib/Button" --lib="lib/Fsm" --lib="lib/LEDFader"--lib="lib/MIDI" --lib="lib/StackArray" - platformio ci --board=teensy31 --lib="lib/Average" --lib="lib/Button" --lib="lib/Fsm" --lib="lib/LEDFader"--lib="lib/MIDI" --lib="lib/StackArray" --lib="lib/Streaming" --lib="lib/digitalWriteFast"
