language: python
python:
  - "2.7"
sudo: false
cache:
  pip: true
  directories:
    - "~/.platformio"
env:
  - PLATFORMIO_CI_SRC=src PLATFORMIO_BUILD_FLAGS="-O3 -Wall -flto=3"
install:
#   - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
  - pip install -U setuptools pip
  - pip install -U platformio
script:
  - platformio ci --board=teensy31 --lib="lib/Average" --lib="lib/Button" --lib="lib/Fsm" --lib="lib/LEDFader" --lib="lib/MIDI" --lib="lib/StackArray"
